version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: yarn
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    # Increase the version requirements
    # only when required
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "yarn"