name: Pipeline
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Setup Latest Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: latest
          
      - name: Install dependencies
        run: yarn install

      - name: Build the React app
        run: yarn build
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with: 
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=santoshshinde2012
            -Dsonar.projectKey=santoshshinde2012_speedyreact-kit
            -Dsonar.projectName=speedyreact-kit
            -Dsonar.projectVersion=1.0
            -Dsonar.language=ts
            -Dsonar.sources=src
            -Dsonar.inclusions=src/**/*.{ts,tsx}
            -Dsonar.tests=src/**/*test.tsx
            -Dsonar.coverage.exclusions=src/**/*test.tsx,.yarn/*, node_modules/*,coverage/lcov-report/*,jest.config.ts,setupTests.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info 
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.verbose=false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git init
          git add -A
          git commit -m "deploy"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main:gh-pages

    env:
      CI: true